# Generated by Django 5.1.6 on 2025-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_tag_alter_category_name_course_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="courses.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
