# Generated by Django 5.1.6 on 2025-02-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_tags_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(upload_to="lessons/%Y/%m/"),
        ),
    ]
